# Generated by Django 3.1.2 on 2020-10-17 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionpost',
            name='read',
        ),
    ]
